# Copyright (c) 2023 Sanjib Kumar Sen <mail@sanjibsen.com>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Publish Package to npmjs

on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
